version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=mongodb://root:example@mongo:27017/
      - SECRET_KEY=somesecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example