version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app
    environment:
      - DATABASE_URL=mongodb://root:example@mongo:27017/
      - SECRET_KEY=somesecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - ORIGINS=http://localhost:8080,https://localhost:8080,http://127.0.0.1:8080,https://127.0.0.1:8080
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  caddy-data:
  caddy-config:
  dbdata6: