version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=mongodb://root:example@mongo:27017/

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: fastapi