---
name: Checks
 
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          (cd ./backend && docker-compose up -d)
          sleep 5
          (cd ./backend && docker-compose run --rm app sh -c "pytest")
      - name: Formating
        run: (cd ./backend && docker-compose run --rm app sh -c "flake8" )