---
name: Checks
 
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          docker-compose up -d mongo backend
          sleep 5
          docker-compose run --rm backend sh -c "pytest"
      - name: Formating
        run: docker-compose run --rm backend sh -c "flake8"